query adminApplicationsTable(
    $after: String
    $before: String
    $first: Int
    $last: Int
    $filter: ApplicationsFilter!
) {
    applications(
        after: $after
        before: $before
        first: $first
        last: $last
        filter: $filter
    ) {
        pageInfo {
            hasNextPage
            hasPreviousPage
            endCursor
        }
        edges {
            cursor
            node {
                id
                formId
                createdOn
                currentStatus {
                    status
                }
                user {
                    email
                    firstName
                    lastName
                    phoneCode
                    phoneNumber
                    studentProfile {
                        collegeId
                    }
                }
            }
        }
    }
}

query adminApplicationsTableFilterOptions {
    convocatories {
        id
        privateLabel
        form {
            id
        }
    }
    colleges {
        id
        name
    }
}
