mutation signUpToTalk($uuid: String!) {
    signUpToTalk(talkUuid: $uuid) {
        ... on TalkInscription {
            __typename
            number
        }
        ... on ApiError {
            __typename
            message
        }
    }
}

mutation assistToTalk($talkUuid: String!) {
    assistToTalk(talkUuid: $talkUuid) {
        ... on AssistToTalkLink {
            __typename
            url
        }
        ... on ApiError {
            __typename
            message
        }
    }
}
