query adminConvocatoriesTable {
    convocatories {
        id
        form {
            id
            uuid
        }
        kind
        order
        privateLabel
        talk {
            startDate
            endDate
        }
        countAddingsFromDate
        countAddingsTillDate
    }
}
