query user {
    user {
        id
        email
        firstName
        lastName
        isStudent
        isTeacher
        isAdmin
        isSuperAdmin
        teacherProfile {
            isVerified
        }
    }
}
