import { ApplicationStatus, FormFieldType } from '@/api/graphql';
import { FormBuilderFormValues } from '..';

export const PLATZI_FORM_TEMPLATE: FormBuilderFormValues = {
    fieldsIDsToDelete: [],
    openDatetime: null,
    closeDatetime: null,
    termsAcceptanceCloseDatetime: null,
    termsAcceptanceOpenDatetime: null,
    title: 'Beca Platzi - BuenaOnda Talks',
    fields: [
        {
            id: 301,
            description:
                'Al completar este formulario, declaras formalmente que asististe a la charla informativa sobre la Beca BuenaOnda Talks, que conoces y aceptas tanto los requisitos necesarios como las exigencias y características del la Beca, y que tienes plena conformidad con ambas condiciones. De no ser así, tu solicitud no será aceptada.',
            isRequired: true,
            maxLength: 144,
            minLength: 0,
            isImportant: true,
            options: [
                {
                    id: 817,
                    label: 'Estoy de acuerdo, comenzar mi postulación',
                    uuid: 'b6b42a62-ac93-4583-b8ec-0d08fe137b80',
                    order: 0,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 818,
                    label: 'No deseo participar',
                    uuid: '65745a94-6942-4b82-a0e1-bb2ee1f0ac1c',
                    order: 10,
                    automaticResult: ApplicationStatus.Declined,
                    automaticResultObservations: 'No deseas participar',
                },
            ],
            title: 'Antes de comenzar',
            order: 0,
            type: FormFieldType.RadioBox,
            uuid: '8fb0eb9d-594a-4db2-9743-157fa15b4543',
            dependsOnFieldUUID: null,
            dependsOnFieldOptionUUID: null,
        },
        {
            id: 302,
            description: '',
            isRequired: true,
            maxLength: 144,
            minLength: 0,
            isImportant: false,
            options: [],
            title: '¿En qué región vives?',
            order: 10,
            type: FormFieldType.Text,
            uuid: 'cae8be96-c04e-4db9-8ec8-4a8a80cf9144',
            dependsOnFieldUUID: '8fb0eb9d-594a-4db2-9743-157fa15b4543',
            dependsOnFieldOptionUUID: 'b6b42a62-ac93-4583-b8ec-0d08fe137b80',
        },
        {
            id: 303,
            description: '',
            isRequired: true,
            maxLength: 144,
            minLength: 0,
            isImportant: false,
            options: [],
            title: '¿En qué comuna vives?',
            order: 20,
            type: FormFieldType.Text,
            uuid: 'f3bac282-825e-4f1e-bea5-d6b5d8a7c8ce',
            dependsOnFieldUUID: '8fb0eb9d-594a-4db2-9743-157fa15b4543',
            dependsOnFieldOptionUUID: 'b6b42a62-ac93-4583-b8ec-0d08fe137b80',
        },
        {
            id: 304,
            description:
                'De ser así y de obtener la beca, tendrás que leer y aceptar las condiciones del programa.',
            isRequired: true,
            maxLength: 144,
            minLength: 0,
            isImportant: true,
            options: [
                {
                    id: 819,
                    label: 'No',
                    uuid: '76762e6a-9eee-4040-82b8-0c55b9db9247',
                    order: 0,
                    automaticResult: ApplicationStatus.Declined,
                    automaticResultObservations: 'No cuentas con 100% de compromiso',
                },
                {
                    id: 820,
                    label: 'Sí',
                    uuid: '6b4664c9-3fc3-4982-8594-6c6835dc3358',
                    order: 10,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
            ],
            title: '¿Tienes 100% de compromiso y disponibilidad para cursar este programa?',
            order: 30,
            type: FormFieldType.RadioBox,
            uuid: 'ba4a858c-ffdc-4ffa-92c3-745bcd8a6e04',
            dependsOnFieldUUID: '8fb0eb9d-594a-4db2-9743-157fa15b4543',
            dependsOnFieldOptionUUID: 'b6b42a62-ac93-4583-b8ec-0d08fe137b80',
        },
        {
            id: 305,
            description: '',
            isRequired: true,
            maxLength: 144,
            minLength: 0,
            isImportant: true,
            options: [
                {
                    id: 821,
                    label: 'Sí',
                    uuid: '2545d8c3-40fd-4743-bdfb-559c3c7d72b4',
                    order: 0,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 822,
                    label: 'No',
                    uuid: 'cf8da3cb-db7c-4c46-9f9c-b86e116f5377',
                    order: 10,
                    automaticResult: ApplicationStatus.Pending,
                    automaticResultObservations: 'No cuentas con internet',
                },
            ],
            title: '¿Cuentas con una conexión a Internet de banda ancha/fibra/internet móvil disponible para cursar el programa de la beca?',
            order: 40,
            type: FormFieldType.RadioBox,
            uuid: '83003b22-289e-4f48-a0a1-c36099e1a810',
            dependsOnFieldUUID: '8fb0eb9d-594a-4db2-9743-157fa15b4543',
            dependsOnFieldOptionUUID: 'b6b42a62-ac93-4583-b8ec-0d08fe137b80',
        },
        {
            id: 306,
            description: '',
            isRequired: true,
            maxLength: 144,
            minLength: 0,
            isImportant: false,
            options: [
                {
                    id: 823,
                    label: 'Excelente, puedo jugar online con un ping super bajo',
                    uuid: '034dab4d-59b5-4b53-8545-0cc76d8a6f0a',
                    order: 0,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 824,
                    label: 'Buena, puedo ver YouTube en Full HD, 1080p sin ningún retraso',
                    uuid: '0a1d370e-c22b-4b3c-aa8b-112640f1ec12',
                    order: 10,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 825,
                    label: 'Regular, puedo ver YouTube en HD, 720p sin retraso',
                    uuid: '2bfa8446-1a3e-46b3-9f6a-736b3b6789e8',
                    order: 20,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 826,
                    label: 'Muy lenta, hasta YouTube se queda pegado',
                    uuid: '03715082-6998-4096-bc98-dd663a5f684c',
                    order: 30,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
            ],
            title: '¿Cuánta velocidad de internet tienes?',
            order: 50,
            type: FormFieldType.RadioBox,
            uuid: 'dee6b144-dad3-4c6a-8fd5-18053e254bea',
            dependsOnFieldUUID: '8fb0eb9d-594a-4db2-9743-157fa15b4543',
            dependsOnFieldOptionUUID: 'b6b42a62-ac93-4583-b8ec-0d08fe137b80',
        },
        {
            id: 307,
            description: '¿Cuál de estas opciones aplica en tu caso?',
            isRequired: true,
            maxLength: 144,
            minLength: 0,
            isImportant: true,
            options: [
                {
                    id: 827,
                    label: 'Tengo una computadora propia',
                    uuid: '45e8ffc7-1ed6-4532-b996-d901b64ff575',
                    order: 0,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 828,
                    label: 'Tengo una computadora que comparto con familiares y/o amigos',
                    uuid: '0eead526-d8b5-4825-9cbd-7097930cc068',
                    order: 10,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 829,
                    label: 'No tengo una computadora',
                    uuid: '3239b491-2d16-42a1-a299-b99c1ede7418',
                    order: 20,
                    automaticResult: ApplicationStatus.Pending,
                    automaticResultObservations: 'No cuentas con computador',
                },
                {
                    id: 830,
                    label: 'Otro caso no descrito aquí',
                    uuid: '9dd202f6-25f5-4aeb-a90f-89f36e5e0d2e',
                    order: 30,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
            ],
            title: 'Sobre tu acceso a una computadora',
            order: 60,
            type: FormFieldType.RadioBox,
            uuid: '5d880db7-58a4-404f-a2da-715ecf4fa278',
            dependsOnFieldUUID: '8fb0eb9d-594a-4db2-9743-157fa15b4543',
            dependsOnFieldOptionUUID: 'b6b42a62-ac93-4583-b8ec-0d08fe137b80',
        },
        {
            id: 308,
            description:
                'Es rápida o lenta. Que es lo más exigente que puedes hacer en ella.',
            isRequired: true,
            maxLength: 500,
            minLength: 0,
            isImportant: false,
            options: [],
            title: 'Cuéntanos más sobre tu acceso a una computadora',
            order: 70,
            type: FormFieldType.Textarea,
            uuid: '511b89d6-811c-4168-983e-947df02566f2',
            dependsOnFieldUUID: '5d880db7-58a4-404f-a2da-715ecf4fa278',
            dependsOnFieldOptionUUID: '9dd202f6-25f5-4aeb-a90f-89f36e5e0d2e',
        },
        {
            id: 309,
            description: '',
            isRequired: true,
            maxLength: 144,
            minLength: 0,
            isImportant: false,
            options: [
                {
                    id: 831,
                    label: 'Sí',
                    uuid: 'a989535d-13ad-4de7-8e66-0e86bcddb164',
                    order: 0,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 832,
                    label: 'No',
                    uuid: '9420cffe-5d7c-44f9-b2db-435d46309485',
                    order: 10,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 833,
                    label: 'No tengo computadora',
                    uuid: 'dc99014b-813f-474f-af1d-71081b5a422f',
                    order: 20,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
            ],
            title: '¿Sabes qué sistema operativo tiene tu computadora?',
            order: 80,
            type: FormFieldType.RadioBox,
            uuid: '5dcbc0e2-b4d8-43ba-beb4-2cdacedcd4a1',
            dependsOnFieldUUID: '5d880db7-58a4-404f-a2da-715ecf4fa278',
            dependsOnFieldOptionUUID: '9dd202f6-25f5-4aeb-a90f-89f36e5e0d2e',
        },
        {
            id: 310,
            description: '',
            isRequired: true,
            maxLength: 144,
            minLength: 0,
            isImportant: false,
            options: [
                {
                    id: 834,
                    label: 'Otro',
                    uuid: 'dedb1739-fbff-4bf4-b15f-954d02a40d35',
                    order: 0,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 835,
                    label: 'No lo sé',
                    uuid: '23e1faed-911e-4e15-9e21-af985f335fc7',
                    order: 10,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 836,
                    label: 'Distribución Linux',
                    uuid: '68ac1b76-beda-4a09-ac3f-62389e253e2b',
                    order: 20,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 837,
                    label: 'Mac OS',
                    uuid: 'f19aebf2-dd37-4d63-80c9-4c310e229b9a',
                    order: 30,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 838,
                    label: 'Windows',
                    uuid: '934ccce9-10f7-4d07-aaaa-3d51b80e848e',
                    order: 40,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
            ],
            title: '¿Qué sistema operativo tiene tu computadora?',
            order: 90,
            type: FormFieldType.RadioBox,
            uuid: '6aa22a55-3506-4091-b7fb-752ff28ba543',
            dependsOnFieldUUID: '8fb0eb9d-594a-4db2-9743-157fa15b4543',
            dependsOnFieldOptionUUID: 'b6b42a62-ac93-4583-b8ec-0d08fe137b80',
        },
        {
            id: 311,
            description:
                'Los primeros dos cursos sobre estrategias para aprender en línea y de introducción a la programación están pensados para que los termines en un mes si dedicas entre 6 y 9 horas a la semana. ¿Cuántas horas a la semana te comprometes a dedicar?',
            isRequired: true,
            maxLength: 144,
            minLength: 0,
            isImportant: true,
            options: [
                {
                    id: 839,
                    label: '3 horas a la semana',
                    uuid: 'dd46f130-360b-4ba7-ba11-e85fca30653c',
                    order: 0,
                    automaticResult: ApplicationStatus.Declined,
                    automaticResultObservations:
                        'No cuentas con el compromiso de horas mínimas de dedicación a la semana',
                },
                {
                    id: 840,
                    label: '3 a 6 horas a la semana',
                    uuid: '0739ffb4-3366-4902-8ab4-75cf54e287dd',
                    order: 10,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 841,
                    label: '6 a 9 horas a la semana',
                    uuid: '6db8b678-ee2f-4e1a-98c0-8a43f2229457',
                    order: 20,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 842,
                    label: '10 a 15 horas a la semana',
                    uuid: 'a5836aeb-c6f3-4df5-870c-57a2dab0f297',
                    order: 30,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 843,
                    label: 'Más de 15 horas a la semana',
                    uuid: 'f94fa486-b073-4e4d-b02f-8357ffb3829b',
                    order: 40,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
            ],
            title: 'Sobre tu tiempo disponible para estudiar',
            order: 100,
            type: FormFieldType.RadioBox,
            uuid: 'e528d660-67db-43e0-a097-3eb1d066d60f',
            dependsOnFieldUUID: '8fb0eb9d-594a-4db2-9743-157fa15b4543',
            dependsOnFieldOptionUUID: 'b6b42a62-ac93-4583-b8ec-0d08fe137b80',
        },
        {
            id: 312,
            description: '',
            isRequired: true,
            maxLength: 500,
            minLength: 140,
            isImportant: false,
            options: [],
            title: 'Cuéntanos, en un párrafo, qué haces en tu tiempo libre cuando no estás estudiando',
            order: 110,
            type: FormFieldType.Textarea,
            uuid: '31f61adf-dc3d-471b-8e37-e99cf897009c',
            dependsOnFieldUUID: '8fb0eb9d-594a-4db2-9743-157fa15b4543',
            dependsOnFieldOptionUUID: 'b6b42a62-ac93-4583-b8ec-0d08fe137b80',
        },
        {
            id: 313,
            description:
                'Tu respuesta nos ayuda a conocer mejor a nuestra comunidad y NO AFECTA DE NINGUNA MANERA el resultado de tu solicitud.',
            isRequired: true,
            maxLength: 144,
            minLength: 0,
            isImportant: false,
            options: [
                {
                    id: 844,
                    label: 'No tengo conocimiento de inglés',
                    uuid: '403a0de6-9967-49b5-a856-654a49ec2bb2',
                    order: 0,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 845,
                    label: 'Conocimiento básico',
                    uuid: '4641ea8e-f8f5-4e1a-bacb-b7a34b620e1d',
                    order: 10,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 846,
                    label: 'Conocimiento intermedio',
                    uuid: 'baaba383-0a5d-4525-85bb-b4db8fd4f59b',
                    order: 20,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 847,
                    label: 'Conocimiento avanzado',
                    uuid: '551fa4b2-9da6-4bf2-9f8e-b890291484e1',
                    order: 30,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
            ],
            title: '¿Cuál opción describe mejor tu conocimiento de inglés?',
            order: 120,
            type: FormFieldType.RadioBox,
            uuid: '5870e384-fd7d-4254-b0ef-306236772110',
            dependsOnFieldUUID: '8fb0eb9d-594a-4db2-9743-157fa15b4543',
            dependsOnFieldOptionUUID: 'b6b42a62-ac93-4583-b8ec-0d08fe137b80',
        },
        {
            id: 314,
            description: '',
            isRequired: true,
            maxLength: 144,
            minLength: 0,
            isImportant: false,
            options: [
                {
                    id: 848,
                    label: 'No',
                    uuid: '566f04ec-37ad-4e31-a541-c705d56f48a5',
                    order: 0,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 849,
                    label: 'Aún no lo decido',
                    uuid: '6918853d-cae3-4842-aedb-901441cb7af3',
                    order: 10,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 850,
                    label: 'Sí',
                    uuid: '5f202cf3-ab06-4f81-bd6a-5b195aa31097',
                    order: 20,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
            ],
            title: 'Me gustaría dedicarme profesionalmente a la tecnología',
            order: 130,
            type: FormFieldType.RadioBox,
            uuid: '73c7a951-4c7c-41bb-9cdc-811deda3643c',
            dependsOnFieldUUID: '8fb0eb9d-594a-4db2-9743-157fa15b4543',
            dependsOnFieldOptionUUID: 'b6b42a62-ac93-4583-b8ec-0d08fe137b80',
        },
        {
            id: 315,
            description: 'Responde con un mínimo de 65 caracteres.',
            isRequired: true,
            maxLength: 500,
            minLength: 65,
            isImportant: false,
            options: [],
            title: '¿Qué problema resolverías con tecnología y por qué?',
            order: 140,
            type: FormFieldType.Textarea,
            uuid: 'd6c31dde-62e4-4a88-a5d6-507ee591a941',
            dependsOnFieldUUID: '8fb0eb9d-594a-4db2-9743-157fa15b4543',
            dependsOnFieldOptionUUID: 'b6b42a62-ac93-4583-b8ec-0d08fe137b80',
        },
        {
            id: 316,
            description: '',
            isRequired: true,
            maxLength: 144,
            minLength: 0,
            isImportant: false,
            options: [
                {
                    id: 851,
                    label: 'Nunca',
                    uuid: '83557142-8355-489c-822c-efbe18c60629',
                    order: 0,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 852,
                    label: 'Pocas veces',
                    uuid: 'db49f038-e247-43dc-ab05-ef8f07582942',
                    order: 10,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 853,
                    label: 'Casi Siempre',
                    uuid: '0a725718-a945-4eb2-a922-1b94aa8435eb',
                    order: 20,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 854,
                    label: 'Siempre',
                    uuid: '35c982e9-f98d-4986-8d1d-7a9acbf3b72f',
                    order: 30,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
            ],
            title: 'Cuando empiezo algo, lo termino...',
            order: 150,
            type: FormFieldType.RadioBox,
            uuid: 'e4932029-ebf2-4004-a8cb-585b7881263f',
            dependsOnFieldUUID: '8fb0eb9d-594a-4db2-9743-157fa15b4543',
            dependsOnFieldOptionUUID: 'b6b42a62-ac93-4583-b8ec-0d08fe137b80',
        },
        {
            id: 317,
            description: '',
            isRequired: true,
            maxLength: 144,
            minLength: 0,
            isImportant: false,
            options: [
                {
                    id: 855,
                    label: 'A veces',
                    uuid: 'b95d4bcf-b308-49cf-b9e6-91ca5062fae9',
                    order: 0,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 856,
                    label: 'No',
                    uuid: '3b6dab71-0bfa-4d74-93aa-27050b6669ac',
                    order: 10,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 857,
                    label: 'Sí',
                    uuid: 'dc8c1e24-a06d-4897-86ee-f112c1f4d8a1',
                    order: 20,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
            ],
            title: 'Me gustan los retos difíciles y aprender cosas nuevas.',
            order: 160,
            type: FormFieldType.RadioBox,
            uuid: '14c0b1d4-f4a0-4e81-be40-f035041ed32b',
            dependsOnFieldUUID: '8fb0eb9d-594a-4db2-9743-157fa15b4543',
            dependsOnFieldOptionUUID: 'b6b42a62-ac93-4583-b8ec-0d08fe137b80',
        },
        {
            id: 318,
            description: '',
            isRequired: true,
            maxLength: 144,
            minLength: 0,
            isImportant: false,
            options: [
                {
                    id: 858,
                    label: 'Investigo en Internet cómo hacerlo',
                    uuid: '8513c023-aa9d-4adc-8288-2ec43c94810a',
                    order: 0,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 859,
                    label: 'Me frustro al inicio pero después lo logro',
                    uuid: '4c07b260-2b0b-4611-91fe-2c2f66955a34',
                    order: 10,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 860,
                    label: 'Le pido a otra persona que lo resuelva',
                    uuid: '2ad64f81-6b11-4a8d-b688-f98b68cd5079',
                    order: 20,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 861,
                    label: 'Abandono la tarea',
                    uuid: '1904b466-6beb-40de-908d-a8a5534ef1a4',
                    order: 30,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
            ],
            title: 'Cuando me doy cuenta de que no tengo la capacidad para resolver un problema...',
            order: 170,
            type: FormFieldType.RadioBox,
            uuid: '8d43d49b-212f-4981-8299-4e424b1f4981',
            dependsOnFieldUUID: '8fb0eb9d-594a-4db2-9743-157fa15b4543',
            dependsOnFieldOptionUUID: 'b6b42a62-ac93-4583-b8ec-0d08fe137b80',
        },
        {
            id: 319,
            description: 'Responde con un mínimo de 65 caracteres.',
            isRequired: true,
            maxLength: 500,
            minLength: 65,
            isImportant: false,
            options: [],
            title: '¿Cuál es el logro del que te sientes más orgullos@?',
            order: 180,
            type: FormFieldType.Textarea,
            uuid: 'fa0e13a9-f743-4ec4-8250-acf264bcf767',
            dependsOnFieldUUID: '8fb0eb9d-594a-4db2-9743-157fa15b4543',
            dependsOnFieldOptionUUID: 'b6b42a62-ac93-4583-b8ec-0d08fe137b80',
        },
        {
            id: 320,
            description: '¡Usa tu imaginación! Responde con un mínimo de 65 caracteres.',
            isRequired: true,
            maxLength: 500,
            minLength: 65,
            isImportant: false,
            options: [],
            title: '¿Por qué quieres esta beca para estudiar programación?',
            order: 190,
            type: FormFieldType.Textarea,
            uuid: '3239e4b4-9351-4338-bbb7-4b7e432391a3',
            dependsOnFieldUUID: '8fb0eb9d-594a-4db2-9743-157fa15b4543',
            dependsOnFieldOptionUUID: 'b6b42a62-ac93-4583-b8ec-0d08fe137b80',
        },
        {
            id: 321,
            description: 'Responde con un mínimo de 65 caracteres.',
            isRequired: true,
            maxLength: 500,
            minLength: 65,
            isImportant: false,
            options: [],
            title: 'Una vez que completes el programa ¿cómo vas a contribuir a tu comunidad y a la comunidad de Buena Onda Talks?',
            order: 200,
            type: FormFieldType.Textarea,
            uuid: 'cbd979cc-1dbb-4420-bfcb-5fde634afb52',
            dependsOnFieldUUID: '8fb0eb9d-594a-4db2-9743-157fa15b4543',
            dependsOnFieldOptionUUID: 'b6b42a62-ac93-4583-b8ec-0d08fe137b80',
        },
    ],
};
