mutation CreateMyStudentProfile {
    createMyStudentProfile {
        id
    }
}

mutation CompleteMyStudentProfile(
    $communeId: Int!
    $collegeId: Int
    $newCollegeName: String
) {
    completeMyStudentProfile(
        communeId: $communeId
        collegeId: $collegeId
        newCollegeName: $newCollegeName
    ) {
        id
    }
}

mutation CreateMyTeacherProfile(
    $communeId: Int!
    $role: String!
    $collegeId: Int
    $newCollegeName: String
) {
    createMyTeacherProfile(
        communeId: $communeId
        role: $role
        collegeId: $collegeId
        newCollegeName: $newCollegeName
    ) {
        id
    }
}
