import { ApplicationStatus, FormFieldType } from '@/api/graphql';
import { FormBuilderFormValues } from '..';

export const DEVF_FORM_TEMPLATE: FormBuilderFormValues = {
    fieldsIDsToDelete: [],
    openDatetime: null,
    closeDatetime: null,
    termsAcceptanceCloseDatetime: null,
    termsAcceptanceOpenDatetime: null,
    title: 'Beca DEV.F - BuenaOnda Talks',
    fields: [
        {
            id: 449,
            description:
                'Al completar este formulario, declaras bajo juramento que asististe a la charla informativa sobre la Beca BuenaOnda Talks, que conoces y aceptas tanto los requisitos necesarios como las exigencias y características del curso que te otorga la Beca, y que tienes plena conformidad con ambas condiciones. De no ser así, tu solicitud podría no ser aceptada.',
            isRequired: true,
            maxLength: 144,
            minLength: 0,
            isImportant: true,
            options: [
                {
                    id: 1132,
                    label: 'Estoy de acuerdo, comenzar mi postulación',
                    uuid: 'ba42992a-f76c-41fd-a9fa-587fb4ecc237',
                    order: 0,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1133,
                    label: 'No deseo participar',
                    uuid: 'b645fbf2-de08-4a8d-b795-251f08269834',
                    order: 10,
                    automaticResult: ApplicationStatus.Declined,
                    automaticResultObservations: 'No deseas participar',
                },
            ],
            title: 'Antes de comenzar',
            order: 0,
            type: FormFieldType.RadioBox,
            uuid: '681cd559-f4c0-44d0-af3d-71e0b2427403',
            dependsOnFieldUUID: null,
            dependsOnFieldOptionUUID: null,
        },
        {
            id: 450,
            description:
                'De ser así y de obtener la beca, tendrás que leer y aceptar las condiciones del programa.\r\n\r\n- Duración 6 meses\r\n- 2 clases a la semana\r\n- La fecha de inicio está por confirmarse\r\n- Curso: Profesional in Coding, Front-end Web Developer',
            isRequired: true,
            maxLength: 144,
            minLength: 0,
            isImportant: true,
            options: [
                {
                    id: 1134,
                    label: 'No',
                    uuid: 'fc7454f0-cfe7-4491-8483-d303bb26cbec',
                    order: 0,
                    automaticResult: ApplicationStatus.Declined,
                    automaticResultObservations: 'No cuentas con 100% de compromiso',
                },
                {
                    id: 1135,
                    label: 'Sí',
                    uuid: 'a7608a1b-1716-462b-b91a-44b2555e9dd2',
                    order: 10,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
            ],
            title: '¿Tienes 100% de compromiso y disponibilidad para cursar este programa?',
            order: 10,
            type: FormFieldType.RadioBox,
            uuid: 'eb496549-a346-4832-8b9d-81f55e86a744',
            dependsOnFieldUUID: '681cd559-f4c0-44d0-af3d-71e0b2427403',
            dependsOnFieldOptionUUID: 'ba42992a-f76c-41fd-a9fa-587fb4ecc237',
        },
        {
            id: 451,
            description:
                'El curso llamado Professional en Coding dura:\r\n\r\n- 6 meses\r\n- con clases 2 veces por semana (lunes y miércoles)\r\n- cada clase dura 3 horas\r\n\r\nAdemás se recomienda dedicar entre 6 y 12 horas extras para estudiar y repasar. \r\n\r\n¿Cuántas horas a la semana le puedes dedicar al programa?',
            isRequired: true,
            maxLength: 144,
            minLength: 0,
            isImportant: true,
            options: [
                {
                    id: 1136,
                    label: '3 horas a la semana',
                    uuid: '6189c9f7-ca3b-4e1c-bb4d-344dbf21648f',
                    order: 0,
                    automaticResult: ApplicationStatus.Declined,
                    automaticResultObservations:
                        'No cuentas con el compromiso de horas mínimas de dedicación a la semana',
                },
                {
                    id: 1137,
                    label: '3 a 6 horas a la semana',
                    uuid: 'b44875c0-30d3-4185-ac62-17b92a65f94d',
                    order: 10,
                    automaticResult: ApplicationStatus.Declined,
                    automaticResultObservations:
                        'No cuentas con el compromiso de horas mínimas de dedicación a la semana',
                },
                {
                    id: 1138,
                    label: '6 a 9 horas a la semana',
                    uuid: '0aa9684c-9390-480b-9c63-ffeb64df151c',
                    order: 20,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1139,
                    label: '10 a 15 horas a la semana',
                    uuid: '589e204d-e858-4f8b-a1db-e9c27a0a47ad',
                    order: 30,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1140,
                    label: 'Más de 15 horas a la semana',
                    uuid: '5bab9b68-3b6f-48f7-afb0-564bb9cf52f6',
                    order: 40,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
            ],
            title: 'Sobre tu tiempo disponible para estudiar',
            order: 20,
            type: FormFieldType.RadioBox,
            uuid: '33908154-8bfc-4a92-80cb-325ce53c9e34',
            dependsOnFieldUUID: '681cd559-f4c0-44d0-af3d-71e0b2427403',
            dependsOnFieldOptionUUID: 'ba42992a-f76c-41fd-a9fa-587fb4ecc237',
        },
        {
            id: 452,
            description:
                'Tu respuesta nos ayuda a conocer mejor a nuestra comunidad y NO AFECTA DE NINGUNA MANERA el resultado de tu solicitud. **Cualquier persona puede aprender con nosotros sin importar su nivel de estudios.**',
            isRequired: true,
            maxLength: 144,
            minLength: 0,
            isImportant: false,
            options: [
                {
                    id: 1141,
                    label: 'Primaria - Enseñanza básica',
                    uuid: '024597e3-679b-49f8-8816-e4286aef1709',
                    order: 0,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1142,
                    label: 'Secundaria - Enseñanza media incompleta',
                    uuid: 'ad4def76-d487-4fa2-91de-16a93aee5e94',
                    order: 10,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1143,
                    label: 'Secundaria - Enseñanza media completa',
                    uuid: 'dc878a48-98c9-44c8-8544-604239d4b02d',
                    order: 20,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1144,
                    label: 'Educación de nivel superior incompleta (Técnico/Universitaria)',
                    uuid: '05ee432e-f9fc-4bca-bd5b-aa6a3ba939e3',
                    order: 30,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1145,
                    label: 'Educación de nivel superior completa (Técnico/Universitaria)',
                    uuid: '9e457799-56bf-4fcf-8b70-4dcfb42def82',
                    order: 40,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
            ],
            title: '¿Cuál es tu último nivel de estudios?',
            order: 30,
            type: FormFieldType.RadioBox,
            uuid: 'befdbd12-2956-4e07-9645-e5f3863f167e',
            dependsOnFieldUUID: '681cd559-f4c0-44d0-af3d-71e0b2427403',
            dependsOnFieldOptionUUID: 'ba42992a-f76c-41fd-a9fa-587fb4ecc237',
        },
        {
            id: 453,
            description:
                'Tu respuesta nos ayuda a conocer mejor a nuestra comunidad y NO AFECTA DE NINGUNA MANERA el resultado de tu solicitud.\r\nLa industria tecnológica ofrece **excelentes oportunidades profesionales para personas con capacidades diferentes** porque les permite trabajar desde casa, entre otras cosas.',
            isRequired: true,
            maxLength: 144,
            minLength: 0,
            isImportant: false,
            options: [
                {
                    id: 1146,
                    label: 'No',
                    uuid: 'c16c4456-076c-4766-9e07-d9fd82ae14fc',
                    order: 0,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1147,
                    label: 'Sí',
                    uuid: '01af933f-0873-4955-8791-65710a4df666',
                    order: 10,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
            ],
            title: '¿Consideras que eres una persona con alguna discapacidad física?',
            order: 40,
            type: FormFieldType.RadioBox,
            uuid: 'efc2c28f-71dc-4861-8a94-198db8fe345d',
            dependsOnFieldUUID: '681cd559-f4c0-44d0-af3d-71e0b2427403',
            dependsOnFieldOptionUUID: 'ba42992a-f76c-41fd-a9fa-587fb4ecc237',
        },
        {
            id: 454,
            description: '',
            isRequired: true,
            maxLength: 144,
            minLength: 0,
            isImportant: false,
            options: [],
            title: 'Cuéntanos un poco más sobre tu discapacidad',
            order: 50,
            type: FormFieldType.Textarea,
            uuid: 'fbc69f61-bdce-410e-a1bc-ddc2ac7785ea',
            dependsOnFieldUUID: '681cd559-f4c0-44d0-af3d-71e0b2427403',
            dependsOnFieldOptionUUID: 'ba42992a-f76c-41fd-a9fa-587fb4ecc237',
        },
        {
            id: 455,
            description:
                'Estamos trabajando para que nuestros programas sean más **incluyentes** y representen la **diversidad que hay en Latinoamérica.** Esta pregunta nos ayuda a entender si estamos en el camino correcto hacia esa meta.',
            isRequired: true,
            maxLength: 144,
            minLength: 0,
            isImportant: false,
            options: [
                {
                    id: 1148,
                    label: 'Afrodescendiente',
                    uuid: '226b42ee-34b8-4af8-b099-a718c0393a10',
                    order: 0,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1149,
                    label: 'Mestizo',
                    uuid: '92eeaa36-8485-495a-9aa4-5fe1817aaa67',
                    order: 10,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1150,
                    label: 'Origen árabe o del Medio Oriente',
                    uuid: '4d682daf-4cfa-475e-9a12-9e4bffa6f8bd',
                    order: 20,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1151,
                    label: 'Origen asiático',
                    uuid: '3c8804a2-b55f-4e4a-8fa9-a8aafe6c9efb',
                    order: 30,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1152,
                    label: 'Origen europeo',
                    uuid: '9267de9c-9e01-437c-b7ea-9410354fe830',
                    order: 40,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1153,
                    label: 'Origen indígena',
                    uuid: '44be47da-5394-4e37-9f58-b3d8bad812e2',
                    order: 50,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1154,
                    label: 'Otro',
                    uuid: 'cd89bf32-233b-46a9-8db7-4cfb71a60b59',
                    order: 60,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
            ],
            title: '¿Con cuál de los siguientes grupos o etnias te sientes más identificado?',
            order: 60,
            type: FormFieldType.RadioBox,
            uuid: '85febd41-cfb7-4a8e-a1d2-bbb44817f07b',
            dependsOnFieldUUID: '681cd559-f4c0-44d0-af3d-71e0b2427403',
            dependsOnFieldOptionUUID: 'ba42992a-f76c-41fd-a9fa-587fb4ecc237',
        },
        {
            id: 456,
            description: '',
            isRequired: true,
            maxLength: 144,
            minLength: 0,
            isImportant: false,
            options: [],
            title: 'Cuéntanos un poco más de tu origen o la etnia con la que te identificas',
            order: 70,
            type: FormFieldType.Textarea,
            uuid: 'cfd50988-a0cd-43fd-bab7-7c9a0ed7b061',
            dependsOnFieldUUID: '681cd559-f4c0-44d0-af3d-71e0b2427403',
            dependsOnFieldOptionUUID: 'ba42992a-f76c-41fd-a9fa-587fb4ecc237',
        },
        {
            id: 457,
            description: '',
            isRequired: true,
            maxLength: 144,
            minLength: 0,
            isImportant: false,
            options: [
                {
                    id: 1155,
                    label: 'Todas las anteriores',
                    uuid: 'e18a3b31-f943-4ef7-99f8-bd96483b6978',
                    order: 0,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1156,
                    label: 'Es una carpeta',
                    uuid: 'bc1acaf1-3a73-477d-b10c-13091fca0c24',
                    order: 10,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1157,
                    label: 'Son los tipos de documentos que guardamos en una computadora. Pueden ser de imagen, música, video, texto y otros.',
                    uuid: '3fea7d2d-1004-4ad4-9028-17cb5097e8c2',
                    order: 20,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1158,
                    label: 'Son programas',
                    uuid: '182d8b7d-070c-409c-ae97-f391d56c3b0b',
                    order: 30,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
            ],
            title: '¿Qué son los archivos?',
            order: 80,
            type: FormFieldType.RadioBox,
            uuid: '90aaa6ad-4a37-4593-a6fd-bd24c68cb8b5',
            dependsOnFieldUUID: '681cd559-f4c0-44d0-af3d-71e0b2427403',
            dependsOnFieldOptionUUID: 'ba42992a-f76c-41fd-a9fa-587fb4ecc237',
        },
        {
            id: 458,
            description: '',
            isRequired: true,
            maxLength: 144,
            minLength: 0,
            isImportant: false,
            options: [
                {
                    id: 1159,
                    label: 'No lo sé',
                    uuid: '04f5970b-bef4-4f46-9636-8b3a56960761',
                    order: 0,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1160,
                    label: 'Intérprete de comandos u órdenes',
                    uuid: 'ebfc451c-b9c7-46d8-b832-3082e2cf5555',
                    order: 10,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1161,
                    label: 'Medio de cobros por tarjeta',
                    uuid: 'f40a295f-2931-430f-8b8d-c28809a7692f',
                    order: 20,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1162,
                    label: 'Mecanismo de comunicación entre procesos',
                    uuid: 'b4645b15-cb62-42df-931c-91aa21b743a6',
                    order: 30,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
            ],
            title: '¿Qué es una terminal?',
            order: 90,
            type: FormFieldType.RadioBox,
            uuid: 'cbfb62ce-a847-4afc-8fea-0f80e4f7190a',
            dependsOnFieldUUID: '681cd559-f4c0-44d0-af3d-71e0b2427403',
            dependsOnFieldOptionUUID: 'ba42992a-f76c-41fd-a9fa-587fb4ecc237',
        },
        {
            id: 459,
            description: '',
            isRequired: true,
            maxLength: 144,
            minLength: 0,
            isImportant: false,
            options: [
                {
                    id: 1163,
                    label: 'No sé lo que es un email',
                    uuid: 'f18533c3-920a-4314-9420-4902463223f5',
                    order: 0,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1164,
                    label: 'ejemplo@mail.com',
                    uuid: 'e5bb67db-ddbd-4093-b158-ccb2257c821e',
                    order: 10,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1165,
                    label: 'mali@gmail@com.mx',
                    uuid: '8df40f34-7255-4eef-bbb7-de90533723cb',
                    order: 20,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1166,
                    label: 'https://admin.typeform.com/',
                    uuid: 'f2f66633-5ef3-40c9-9c78-dd7d39f6393c',
                    order: 30,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
            ],
            title: '¿Cuál de las siguientes es un email válido?',
            order: 100,
            type: FormFieldType.RadioBox,
            uuid: '2e00580a-5e70-4511-bf79-24a475d02c04',
            dependsOnFieldUUID: '681cd559-f4c0-44d0-af3d-71e0b2427403',
            dependsOnFieldOptionUUID: 'ba42992a-f76c-41fd-a9fa-587fb4ecc237',
        },
        {
            id: 460,
            description: '',
            isRequired: true,
            maxLength: 144,
            minLength: 0,
            isImportant: false,
            options: [
                {
                    id: 1167,
                    label: 'Es una herramienta para compartir memes',
                    uuid: 'e6680162-046e-4621-99f4-c355f4e68793',
                    order: 0,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1168,
                    label: 'Lenguaje de programación',
                    uuid: 'a1bad05b-884b-4bb5-8a40-7d069831c437',
                    order: 10,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1169,
                    label: 'Conjunto de instrucciones para crear aplicaciones',
                    uuid: 'b4363fac-4f97-4a6e-8522-e679cf71b33c',
                    order: 20,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1170,
                    label: 'Lenguaje de etiquetado de hipertextos',
                    uuid: 'b46ea36a-efdc-427f-85d3-70dd4360d9a4',
                    order: 30,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
            ],
            title: '¿Qué són Javascript, Python, Java, C++?',
            order: 110,
            type: FormFieldType.RadioBox,
            uuid: '8e46dd71-9ab1-4ac7-bfae-a6773959f4a2',
            dependsOnFieldUUID: '681cd559-f4c0-44d0-af3d-71e0b2427403',
            dependsOnFieldOptionUUID: 'ba42992a-f76c-41fd-a9fa-587fb4ecc237',
        },
        {
            id: 461,
            description: '',
            isRequired: true,
            maxLength: 144,
            minLength: 0,
            isImportant: false,
            options: [
                {
                    id: 1171,
                    label: 'Tipo de documento',
                    uuid: '1686343c-6bf7-4524-bbe0-48ec19efd43d',
                    order: 0,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1172,
                    label: 'Software para manejo de un banco',
                    uuid: 'f159737e-949c-4ae5-aed6-563bef3867e8',
                    order: 10,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1173,
                    label: 'Conjunto de datos organizados y almacenados de forma ordenada',
                    uuid: '443a1adb-6e79-41a4-abe0-c948f2c25be1',
                    order: 20,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1174,
                    label: 'Conjunto de algoritmos almacenados',
                    uuid: 'deca7ad8-2bd0-46a7-8839-d463b30b37a4',
                    order: 30,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
            ],
            title: '¿Qué es una base de datos?',
            order: 120,
            type: FormFieldType.RadioBox,
            uuid: '57ddb465-1f0d-42af-8136-0b393a152a0a',
            dependsOnFieldUUID: '681cd559-f4c0-44d0-af3d-71e0b2427403',
            dependsOnFieldOptionUUID: 'ba42992a-f76c-41fd-a9fa-587fb4ecc237',
        },
        {
            id: 462,
            description: '',
            isRequired: true,
            maxLength: 144,
            minLength: 0,
            isImportant: false,
            options: [
                {
                    id: 1175,
                    label: 'Un método matemático',
                    uuid: 'ebc17661-a149-4d08-a2a9-6918008e123f',
                    order: 0,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1176,
                    label: 'Un espacio reservado en memoria',
                    uuid: 'a0a6301e-6e1a-48ee-83a5-3a7c3957df8a',
                    order: 10,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1177,
                    label: 'Algo que varía mucho',
                    uuid: 'a83bdabf-caba-40e4-b6a9-e5eef2ef80c7',
                    order: 20,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1178,
                    label: 'Una colección de datos almacenados',
                    uuid: 'cd2060a0-4cca-46b6-95a3-b41df85f3c95',
                    order: 30,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
            ],
            title: '¿Qué es una variable?',
            order: 130,
            type: FormFieldType.RadioBox,
            uuid: '7074f909-ecd3-498d-9ed7-beb19eb5d8b6',
            dependsOnFieldUUID: '681cd559-f4c0-44d0-af3d-71e0b2427403',
            dependsOnFieldOptionUUID: 'ba42992a-f76c-41fd-a9fa-587fb4ecc237',
        },
        {
            id: 463,
            description: '',
            isRequired: true,
            maxLength: 144,
            minLength: 0,
            isImportant: false,
            options: [
                {
                    id: 1179,
                    label: 'Permite preguntar de la vida, el universo, y todo lo demás',
                    uuid: '94cb80c1-b49d-43df-9dd8-6b54110d272c',
                    order: 0,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1180,
                    label: 'Permite repetir varias veces un bloque de código',
                    uuid: '93768647-0122-4ea8-bebb-e50ee4acb4e0',
                    order: 10,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1181,
                    label: 'Permite dividir el código en dos partes',
                    uuid: 'd4c1cba1-fe3e-4597-a964-645c70e3674b',
                    order: 20,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1182,
                    label: 'Permite tomar decisiones',
                    uuid: '49ec1a01-3876-4a18-9a86-5986fc6c7d99',
                    order: 30,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
            ],
            title: '¿Qué hace la sentencia IF?',
            order: 140,
            type: FormFieldType.RadioBox,
            uuid: 'eba881be-c5aa-476d-99ab-a25e8dfa1965',
            dependsOnFieldUUID: '681cd559-f4c0-44d0-af3d-71e0b2427403',
            dependsOnFieldOptionUUID: 'ba42992a-f76c-41fd-a9fa-587fb4ecc237',
        },
        {
            id: 464,
            description: '',
            isRequired: true,
            maxLength: 144,
            minLength: 0,
            isImportant: false,
            options: [
                {
                    id: 1183,
                    label: 'Actualizar el sitio web',
                    uuid: '8c5b880b-5ed9-4c2c-989b-e4d02d5a07ae',
                    order: 0,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1184,
                    label: 'Diseñar la arquitectura del sitio',
                    uuid: '48709de5-2b24-4082-aa6e-2e463eaa0325',
                    order: 10,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1185,
                    label: 'Crear páginas web',
                    uuid: '11f4de06-ca21-40ba-bdbd-2a1ef42b315d',
                    order: 20,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1186,
                    label: 'Arreglar físicamente una computadora',
                    uuid: '06fd66de-a61a-408d-b254-832526dce947',
                    order: 30,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
            ],
            title: '¿Qué actividades NO hace un/a programador/a web de manera profesional?',
            order: 150,
            type: FormFieldType.RadioBox,
            uuid: '4d233d6f-b615-43e0-b3e1-03b1956ccf80',
            dependsOnFieldUUID: '681cd559-f4c0-44d0-af3d-71e0b2427403',
            dependsOnFieldOptionUUID: 'ba42992a-f76c-41fd-a9fa-587fb4ecc237',
        },
        {
            id: 465,
            description: '',
            isRequired: true,
            maxLength: 144,
            minLength: 0,
            isImportant: false,
            options: [
                {
                    id: 1187,
                    label: 'Middle-end',
                    uuid: 'c075ea76-dbc6-4a41-80f5-85111faa517c',
                    order: 0,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1188,
                    label: 'Dev Ops',
                    uuid: '68a9564a-f7a7-464e-885f-cce19c54d7da',
                    order: 10,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1189,
                    label: 'Backend',
                    uuid: '8ea22700-f7fa-4661-9804-6a5f499c931d',
                    order: 20,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
                {
                    id: 1190,
                    label: 'Frontend',
                    uuid: '6da4e5f1-3efc-4b0a-9a7b-af0b7400e410',
                    order: 30,
                    automaticResult: null,
                    automaticResultObservations: null,
                },
            ],
            title: '¿Cuál no es un área para trabajar en programación?',
            order: 160,
            type: FormFieldType.RadioBox,
            uuid: '0eba68a4-b6c5-4b51-bcda-1831daca5e23',
            dependsOnFieldUUID: '681cd559-f4c0-44d0-af3d-71e0b2427403',
            dependsOnFieldOptionUUID: 'ba42992a-f76c-41fd-a9fa-587fb4ecc237',
        },
    ],
};
